### ISSUE TITLE
Client Timeout not being followed

### ISSUE THREAD

**Issue by dombarnes** [ConvertAPI/convertapi-dotnet#43]
We currently use your library to convert doc and xls files. We have hit an issue where some XLS files take a long time to convert. Using the ruby libary, they take around 140s to complete.
While using the dotnet library, we set
```
ConvertApiResponse convertToPdf = null;
var convertApi = new ConvertApi(_appSettings.ConvertAPIKey);
convertApi.SetTimeOut(1200); //20 minutes
using (var stream = file.OpenReadStream())
{
    convertToPdf = await convertApi.ConvertAsync(ext, "pdf",
        new ConvertApiFileParam(stream, filename)
    );
}
```

However our conversion gets killed after 100 seconds.
```
An unhandled exception has occurred while executing the request.
      System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
       ---> System.TimeoutException: The operation was canceled.
       ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
       ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
       ---> System.Net.Sockets.SocketException (89): Operation canceled
         --- End of inner exception stack trace ---
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
         at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
         at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         --- End of inner exception stack trace ---
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         at ConvertApiDotNet.HttpRequestExtensions.PostAsync(IConvertApiHttpClient convertApiHttpClient, Uri url, Int32 timeOut, HttpContent content)
         at ConvertApiDotNet.ConvertApi.ConvertAsync(String fromFormat, String toFormat, IEnumerable`1 parameters)
         at ConvertApiDotNet.ConvertApi.ConvertAsync(String fromFormat, String toFormat, ConvertApiBaseParam[] parameters)
```

Platform Info:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.6
 OS Platform: Darwin
 RID:         osx.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.202/

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76
```
Package Info:
`<PackageReference Include="ConvertApi" Version="3.0.7" />`

**Comment by dombarnes** [comment]
For reference, we've managed to patch around this
```
var convertApiHttpClient = new DefaultConvertApiHttpClient();
convertApiHttpClient.Client.Timeout = TimeSpan.FromSeconds(1200);
var convertApi = new ConvertApi(_appSettings.ConvertAPIKey, convertApiHttpClient);
```

**Comment by tomasr78** [comment]
We will look at this and release a fix in near future. Your current implementation will work fine.

**Comment by tomasr78** [comment]
We just released a new 3.0.8  version https://www.nuget.org/packages/ConvertApi#versions-body-tab
Please try to update and it should fix the problem. The `SetTimeOut(1200);` method is removed and the default is `900` seconds as it is set in the converter https://www.convertapi.com/xlsx-to-pdf

If you would like to increase timeout you can do that setting TimeOut as parameter:

```
var thumbnail = await convertApi.ConvertAsync("xlsx", "pdf",
    new ConvertApiFileParam(file),
    new ConvertApiParam("TimeOut", "1200")
);
```

**Comment by tomasr78** [comment]
related https://github.com/ConvertAPI/convertapi-dotnet/issues/24
